// (c) Meta Platforms, Inc. and affiliates. Confidential and proprietary.

/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using RosSharp.RosBridgeClient.MessageTypes.Geometry;

namespace RosSharp.RosBridgeClient.MessageTypes.EyefulRos
{
    public class SendCapturePoseRequest : Message
    {
        public const string RosMessageName = "eyeful_ros_msgs/srv/SendCapturePose";

        public Pose pose { get; set; }

        public SendCapturePoseRequest()
        {
            this.pose = new Pose();
        }

        public SendCapturePoseRequest(Pose pose)
        {
            this.pose = pose;
        }
    }
}
