// Copyright (c) Meta Platforms, Inc. and affiliates.

/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

namespace RosSharp.RosBridgeClient.MessageTypes.EyefulRos
{
    public class SetIsoResponse : Message
    {
        public const string RosMessageName = "eyeful_ros_msgs/srv/SetIso";

        public int success { get; set; }
        public string message { get; set; }

        public SetIsoResponse()
        {
            this.success = 0;
            this.message = "";
        }

        public SetIsoResponse(int success, string message)
        {
            this.success = success;
            this.message = message;
        }
    }
}
