// (c) Meta Platforms, Inc. and affiliates. Confidential and proprietary.

/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

namespace RosSharp.RosBridgeClient.MessageTypes.EyefulRos
{
    public class SetIsoRequest : Message
    {
        public const string RosMessageName = "eyeful_ros_msgs/srv/SetIso";

        public int iso { get; set; }
        public int batch_id { get; set; }
        // Which part of the batch capture it is on (0 for first, 1 for second)

        public SetIsoRequest()
        {
            this.iso = 0;
            this.batch_id = 0;
        }

        public SetIsoRequest(int iso, int batch_id)
        {
            this.iso = iso;
            this.batch_id = batch_id;
        }
    }
}
