// Copyright (c) Meta Platforms, Inc. and affiliates.

/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

namespace RosSharp.RosBridgeClient.MessageTypes.EyefulRos
{
    public class SetShutterRequest : Message
    {
        public const string RosMessageName = "eyeful_ros_msgs/srv/SetShutter";

        public string shutter { get; set; }
        public int batch_id { get; set; }
        // Which part of the batch capture it is on (0 for first, 1 for second)

        public SetShutterRequest()
        {
            this.shutter = "";
            this.batch_id = 0;
        }

        public SetShutterRequest(string shutter, int batch_id)
        {
            this.shutter = shutter;
            this.batch_id = batch_id;
        }
    }
}
