// (c) Meta Platforms, Inc. and affiliates. Confidential and proprietary.

/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

namespace RosSharp.RosBridgeClient.MessageTypes.EyefulRos
{
    public class TriggerCaptureRequest : Message
    {
        public const string RosMessageName = "eyeful_ros_msgs/srv/TriggerCapture";

        public bool move_forward { get; set; }

        public TriggerCaptureRequest()
        {
            this.move_forward = false;
        }

        public TriggerCaptureRequest(bool move_forward)
        {
            this.move_forward = move_forward;
        }
    }
}
