// Copyright (c) Meta Platforms, Inc. and affiliates.

/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using RosSharp.RosBridgeClient.MessageTypes.Geometry;

namespace RosSharp.RosBridgeClient.MessageTypes.EyefulRos
{
    public class CapturePoseList : Message
    {
        public const string RosMessageName = "eyeful_ros_msgs/msg/CapturePoseList";

        public Vector3[] capture_poses { get; set; }

        public CapturePoseList()
        {
            this.capture_poses = new Vector3[0];
        }

        public CapturePoseList(Vector3[] capture_poses)
        {
            this.capture_poses = capture_poses;
        }
    }
}
