// (c) Meta Platforms, Inc. and affiliates. Confidential and proprietary.

/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using RosSharp.RosBridgeClient.MessageTypes.Std;
namespace RosSharp.RosBridgeClient.MessageTypes.EyefulRos
{
    public class AdvNavPoseActionResult : ActionResult<AdvNavPoseResult>
    {
        public const string RosMessageName = "eyeful_ros_msgs/action/AdvNavPoseActionResult";

        public AdvNavPoseActionResult() : base()
        {
            this.values = new AdvNavPoseResult();
        }

        public AdvNavPoseActionResult(Header header, string action, sbyte status, bool result, string id, AdvNavPoseResult values) : base(header, action, status, result, id)
        {
            this.values = values;
        }
    }
}
