// (c) Meta Platforms, Inc. and affiliates. Confidential and proprietary.

/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */
using RosSharp.RosBridgeClient.MessageTypes.Std;
using RosSharp.RosBridgeClient.MessageTypes.Action;

namespace RosSharp.RosBridgeClient.MessageTypes.EyefulRos
{
    public class AdvNavPoseActionGoal : ActionGoal<AdvNavPoseGoal>
    {
        public const string RosMessageName = "eyeful_ros_msgs/action/AdvNavPoseActionGoal";

        public AdvNavPoseActionGoal() : base()
        {
            this.args = new AdvNavPoseGoal();
        }

        public AdvNavPoseActionGoal(Header header, GoalInfo goalInfo, AdvNavPoseGoal args) : base(header, goalInfo)
        {
            this.args = args;
        }
    }
}
