// (c) Meta Platforms, Inc. and affiliates. Confidential and proprietary.

/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

namespace RosSharp.RosBridgeClient.MessageTypes.EyefulRos
{
    public class AdvNavPoseFeedback : Message
    {
        public const string RosMessageName = "eyeful_ros_msgs/action/AdvNavPoseFeedback";

        // feedback definition
        public ushort step { get; set; }

        public AdvNavPoseFeedback()
        {
            this.step = 0;
        }

        public AdvNavPoseFeedback(ushort step)
        {
            this.step = step;
        }
    }
}
