// (c) Meta Platforms, Inc. and affiliates. Confidential and proprietary.

/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */


namespace RosSharp.RosBridgeClient.MessageTypes.EyefulRos
{
    public class AdvNavPoseAction : Action<AdvNavPoseActionGoal, AdvNavPoseActionResult, AdvNavPoseActionFeedback, AdvNavPoseGoal, AdvNavPoseResult, AdvNavPoseFeedback>
    {
        public const string RosMessageName = "eyeful_ros_msgs/action/AdvNavPoseAction";

        public AdvNavPoseAction() : base()
        {
            this.action_goal = new AdvNavPoseActionGoal();
            this.action_result = new AdvNavPoseActionResult();
            this.action_feedback = new AdvNavPoseActionFeedback();
        }

    }
}
