// Copyright (c) Meta Platforms, Inc. and affiliates.

#include "eyeful/ErrorString.h"
#include <CrTypes.h>
#define DEFAULT_LOG_CHANNEL "Eyeful"
#include "logging/Logging.h"

namespace error2string {
static const std::unordered_map<CrInt32u, std::string> mapErrorCode{
    {SCRSDK::CrError_None, "CrError_None"},
    {SCRSDK::CrError_Generic, "CrError_Generic"},
    {SCRSDK::CrError_Genric, "CrError_Genric"},
    {SCRSDK::CrError_File, "CrError_File"},
    {SCRSDK::CrError_Connect, "CrError_Connect"},
    {SCRSDK::CrError_Memory, "CrError_Memory"},
    {SCRSDK::CrError_Api, "CrError_Api"},
    {SCRSDK::CrError_Init, "CrError_Init"},
    {SCRSDK::CrError_Polling, "CrError_Polling"},
    {SCRSDK::CrError_Adaptor, "CrError_Adaptor"},
    {SCRSDK::CrError_Device, "CrError_Device"},
    {SCRSDK::CrError_Contents, "CrError_Contents"},
    {SCRSDK::CrError_Monitoring, "CrError_Monitoring"},
    {SCRSDK::CrError_Application, "CrError_Application"},
    {SCRSDK::CrError_Generic_Unknown, "CrError_Generic_Unknown"},
    {SCRSDK::CrError_Generic_Notimpl, "CrError_Generic_Notimpl"},
    {SCRSDK::CrError_Generic_Abort, "CrError_Generic_Abort"},
    {SCRSDK::CrError_Generic_NotSupported, "CrError_Generic_NotSupported"},
    {SCRSDK::CrError_Generic_SeriousErrorNotSupported, "CrError_Generic_SeriousErrorNotSupported"},
    {SCRSDK::CrError_Generic_InvalidHandle, "CrError_Generic_InvalidHandle"},
    {SCRSDK::CrError_Generic_InvalidParameter, "CrError_Generic_InvalidParameter"},
    {SCRSDK::CrError_Genric_Unknown, "CrError_Genric_Unknown"},
    {SCRSDK::CrError_Genric_Notimpl, "CrError_Genric_Notimpl"},
    {SCRSDK::CrError_Genric_Abort, "CrError_Genric_Abort"},
    {SCRSDK::CrError_Genric_NotSupported, "CrError_Genric_NotSupported"},
    {SCRSDK::CrError_Genric_SeriousErrorNotSupported, "CrError_Genric_SeriousErrorNotSupported"},
    {SCRSDK::CrError_Genric_InvalidHandle, "CrError_Genric_InvalidHandle"},
    {SCRSDK::CrError_Genric_InvalidParameter, "CrError_Genric_InvalidParameter"},
    {SCRSDK::CrError_File_Unknown, "CrError_File_Unknown"},
    {SCRSDK::CrError_File_IllegalOperation, "CrError_File_IllegalOperation"},
    {SCRSDK::CrError_File_IllegalParameter, "CrError_File_IllegalParameter"},
    {SCRSDK::CrError_File_EOF, "CrError_File_EOF"},
    {SCRSDK::CrError_File_OutOfRange, "CrError_File_OutOfRange"},
    {SCRSDK::CrError_File_NotFound, "CrError_File_NotFound"},
    {SCRSDK::CrError_File_DirNotFound, "CrError_File_DirNotFound"},
    {SCRSDK::CrError_File_AlreadyOpened, "CrError_File_AlreadyOpened"},
    {SCRSDK::CrError_File_PermissionDenied, "CrError_File_PermissionDenied"},
    {SCRSDK::CrError_File_StorageFull, "CrError_File_StorageFull"},
    {SCRSDK::CrError_File_AlreadyExists, "CrError_File_AlreadyExists"},
    {SCRSDK::CrError_File_TooManyOpenedFiles, "CrError_File_TooManyOpenedFiles"},
    {SCRSDK::CrError_File_ReadOnly, "CrError_File_ReadOnly"},
    {SCRSDK::CrError_File_CantOpen, "CrError_File_CantOpen"},
    {SCRSDK::CrError_File_CantClose, "CrError_File_CantClose"},
    {SCRSDK::CrError_File_CantDelete, "CrError_File_CantDelete"},
    {SCRSDK::CrError_File_CantRead, "CrError_File_CantRead"},
    {SCRSDK::CrError_File_CantWrite, "CrError_File_CantWrite"},
    {SCRSDK::CrError_File_CantCreateDir, "CrError_File_CantCreateDir"},
    {SCRSDK::CrError_File_OperationAbortedByUser, "CrError_File_OperationAbortedByUser"},
    {SCRSDK::CrError_File_UnsupportedOperation, "CrError_File_UnsupportedOperation"},
    {SCRSDK::CrError_File_NotYetCompleted, "CrError_File_NotYetCompleted"},
    {SCRSDK::CrError_File_Invalid, "CrError_File_Invalid"},
    {SCRSDK::CrError_File_StorageNotExist, "CrError_File_StorageNotExist"},
    {SCRSDK::CrError_File_SharingViolation, "CrError_File_SharingViolation"},
    {SCRSDK::CrError_File_Rotation, "CrError_File_Rotation"},
    {SCRSDK::CrError_File_SameNameFull, "CrError_File_SameNameFull"},
    {SCRSDK::CrError_Connect_Unknown, "CrError_Connect_Unknown"},
    {SCRSDK::CrError_Connect_Connect, "CrError_Connect_Connect"},
    {SCRSDK::CrError_Connect_ConnectIP, "CrError_Connect_ConnectIP"},
    {SCRSDK::CrError_Connect_Release, "CrError_Connect_Release"},
    {SCRSDK::CrError_Connect_GetProperty, "CrError_Connect_GetProperty"},
    {SCRSDK::CrError_Connect_SendCommand, "CrError_Connect_SendCommand"},
    {SCRSDK::CrError_Connect_HandlePlugin, "CrError_Connect_HandlePlugin"},
    {SCRSDK::CrError_Connect_Disconnected, "CrError_Connect_Disconnected"},
    {SCRSDK::CrError_Connect_TimeOut, "CrError_Connect_TimeOut"},
    {SCRSDK::CrError_Reconnect_TimeOut, "CrError_Reconnect_TimeOut"},
    {SCRSDK::CrError_Connect_FailRejected, "CrError_Connect_FailRejected"},
    {SCRSDK::CrError_Connect_FailBusy, "CrError_Connect_FailBusy"},
    {SCRSDK::CrError_Connect_FailUnspecified, "CrError_Connect_FailUnspecified"},
    {SCRSDK::CrError_Connect_Cancel, "CrError_Connect_Cancel"},
    {SCRSDK::CrError_Reserved1, "CrError_Reserved1"},
    {SCRSDK::CrError_Reserved2, "CrError_Reserved2"},
    {SCRSDK::CrError_Connect_SessionAlreadyOpened, "CrError_Connect_SessionAlreadyOpened"},
    {SCRSDK::CrError_Connect_ContentsTransfer_NotSupported,
     "CrError_Connect_ContentsTransfer_NotSupported"},
    {SCRSDK::CrError_Connect_SSH_NotSupported, "CrError_Connect_SSH_NotSupported"},
    {SCRSDK::CrError_Connect_SSH_InvalidParameter, "CrError_Connect_SSH_InvalidParameter"},
    {SCRSDK::CrError_Connect_SSH_ServerConnectFailed, "CrError_Connect_SSH_ServerConnectFailed"},
    {SCRSDK::CrError_Connect_SSH_ServerAuthenticationFailed,
     "CrError_Connect_SSH_ServerAuthenticationFailed"},
    {SCRSDK::CrError_Connect_SSH_UserAuthenticationFailed,
     "CrError_Connect_SSH_UserAuthenticationFailed"},
    {SCRSDK::CrError_Connect_SSH_PortfowardFailed, "CrError_Connect_SSH_PortfowardFailed"},
    {SCRSDK::CrError_Connect_SSH_PortForwardFailed, "CrError_Connect_SSH_PortForwardFailed"},
    {SCRSDK::CrError_Connect_SSH_GetFingerprintFailed, "CrError_Connect_SSH_GetFingerprintFailed"},
    {SCRSDK::CrError_Memory_Unknown, "CrError_Memory_Unknown"},
    {SCRSDK::CrError_Memory_OutOfMemory, "CrError_Memory_OutOfMemory"},
    {SCRSDK::CrError_Memory_InvalidPointer, "CrError_Memory_InvalidPointer"},
    {SCRSDK::CrError_Memory_Insufficient, "CrError_Memory_Insufficient"},
    {SCRSDK::CrError_Api_Unknown, "CrError_Api_Unknown"},
    {SCRSDK::CrError_Api_Insufficient, "CrError_Api_Insufficient"},
    {SCRSDK::CrError_Api_InvalidCalled, "CrError_Api_InvalidCalled"},
    {SCRSDK::CrError_Api_NoApplicableInformation, "CrError_Api_NoApplicableInformation"},
    {SCRSDK::CrError_Api_OutOfModelList, "CrError_Api_OutOfModelList"},
    {SCRSDK::CrError_Api_NotSupportModelOfUSB, "CrError_Api_NotSupportModelOfUSB"},
    {SCRSDK::CrError_Api_NotSupportModelOfEthernet, "CrError_Api_NotSupportModelOfEthernet"},
    {SCRSDK::CrError_Api_InvalidSerialNumber, "CrError_Api_InvalidSerialNumber"},
    {SCRSDK::CrError_Api_InvalidIpAddress, "CrError_Api_InvalidIpAddress"},
    {SCRSDK::CrError_Api_InvalidMacAddress, "CrError_Api_InvalidMacAddress"},
    {SCRSDK::CrError_Api_PasswordLengthOverMax, "CrError_Api_PasswordLengthOverMax"},
    {SCRSDK::CrError_Api_PasswordIncludesInvalidCharacter,
     "CrError_Api_PasswordIncludesInvalidCharacter"},
    {SCRSDK::CrError_Polling_Unknown, "CrError_Polling_Unknown"},
    {SCRSDK::CrError_Polling_InvalidVal_Intervals, "CrError_Polling_InvalidVal_Intervals"},
    {SCRSDK::CrError_Adaptor_Unknown, "CrError_Adaptor_Unknown"},
    {SCRSDK::CrError_Adaptor_InvaildProperty, "CrError_Adaptor_InvaildProperty"},
    {SCRSDK::CrError_Adaptor_InvalidProperty, "CrError_Adaptor_InvalidProperty"},
    {SCRSDK::CrError_Adaptor_GetInfo, "CrError_Adaptor_GetInfo"},
    {SCRSDK::CrError_Adaptor_Create, "CrError_Adaptor_Create"},
    {SCRSDK::CrError_Adaptor_SendCommand, "CrError_Adaptor_SendCommand"},
    {SCRSDK::CrError_Adaptor_HandlePlugin, "CrError_Adaptor_HandlePlugin"},
    {SCRSDK::CrError_Adaptor_CreateDevice, "CrError_Adaptor_CreateDevice"},
    {SCRSDK::CrError_Adaptor_EnumDecvice, "CrError_Adaptor_EnumDecvice"},
    {SCRSDK::CrError_Adaptor_EnumDevice, "CrError_Adaptor_EnumDevice"},
    {SCRSDK::CrError_Adaptor_Reset, "CrError_Adaptor_Reset"},
    {SCRSDK::CrError_Adaptor_Read, "CrError_Adaptor_Read"},
    {SCRSDK::CrError_Adaptor_Phase, "CrError_Adaptor_Phase"},
    {SCRSDK::CrError_Adaptor_DataToWiaItem, "CrError_Adaptor_DataToWiaItem"},
    {SCRSDK::CrError_Adaptor_DeviceBusy, "CrError_Adaptor_DeviceBusy"},
    {SCRSDK::CrError_Adaptor_Escape, "CrError_Adaptor_Escape"},
    {SCRSDK::CrError_Device_Unknown, "CrError_Device_Unknown"},
    {SCRSDK::CrError_Contents_Unknown, "CrError_Contents_Unknown"},
    {SCRSDK::CrError_Contents_Reserved1, "CrError_Contents_Reserved1"},
    {SCRSDK::CrError_Contents_InvalidHandle, "CrError_Contents_InvalidHandle"},
    {SCRSDK::CrError_Contents_DateFolderList_NotRetrieved,
     "CrError_Contents_DateFolderList_NotRetrieved"},
    {SCRSDK::CrError_Contents_ContentsList_NotRetrieved,
     "CrError_Contents_ContentsList_NotRetrieved"},
    {SCRSDK::CrError_Contents_Transfer_Unsuccess, "CrError_Contents_Transfer_Unsuccess"},
    {SCRSDK::CrError_Contents_Transfer_Cancel, "CrError_Contents_Transfer_Cancel"},
    {SCRSDK::CrError_Contents_RejectRequest, "CrError_Contents_RejectRequest"},
    {SCRSDK::CrError_Monitoring_Unknown, "CrError_Monitoring_Unknown"},
    {SCRSDK::CrError_Monitoring_InvalidCalled_AlreadyStart,
     "CrError_Monitoring_InvalidCalled_AlreadyStart"},
    {SCRSDK::CrError_Monitoring_InvalidCalled_AlreadyStop,
     "CrError_Monitoring_InvalidCalled_AlreadyStop"},
    {SCRSDK::CrWarning_Unknown, "CrWarning_Unknown"},
    {SCRSDK::CrWarning_Connect_Reconnected, "CrWarning_Connect_Reconnected"},
    {SCRSDK::CrWarning_Connect_Reconnecting, "CrWarning_Connect_Reconnecting"},
    {SCRSDK::CrWarning_File_StorageFull, "CrWarning_File_StorageFull"},
    {SCRSDK::CrWarning_SetFileName_Failed, "CrWarning_SetFileName_Failed"},
    {SCRSDK::CrWarning_GetImage_Failed, "CrWarning_GetImage_Failed"},
    {SCRSDK::CrWarning_FailedToSetCWB, "CrWarning_FailedToSetCWB"},
    {SCRSDK::CrWarning_NetworkErrorOccurred, "CrWarning_NetworkErrorOccurred"},
    {SCRSDK::CrWarning_NetworkErrorRecovered, "CrWarning_NetworkErrorRecovered"},
    {SCRSDK::CrWarning_Format_Failed, "CrWarning_Format_Failed"},
    {SCRSDK::CrWarning_Format_Invalid, "CrWarning_Format_Invalid"},
    {SCRSDK::CrWarning_Format_Complete, "CrWarning_Format_Complete"},
    {SCRSDK::CrWarning_FTPTransferSetting_Read_Result_Invalid,
     "CrWarning_FTPTransferSetting_Read_Result_Invalid"},
    {SCRSDK::CrWarning_FTPTransferSetting_Read_Result_OK,
     "CrWarning_FTPTransferSetting_Read_Result_OK"},
    {SCRSDK::CrWarning_FTPTransferSetting_Read_Result_NG,
     "CrWarning_FTPTransferSetting_Read_Result_NG"},
    {SCRSDK::CrWarning_FTPTransferSetting_Read_Result_NG_password,
     "CrWarning_FTPTransferSetting_Read_Result_NG_password"},
    {SCRSDK::CrWarning_FTPTransferSetting_Read_Result_DeviceBusy,
     "CrWarning_FTPTransferSetting_Read_Result_DeviceBusy"},
    {SCRSDK::CrWarning_Exposure_Started, "CrWarning_Exposure_Started"},
    {SCRSDK::CrWarning_DateTime_Setting_Result_Invalid,
     "CrWarning_DateTime_Setting_Result_Invalid"},
    {SCRSDK::CrWarning_DateTime_Setting_Result_OK, "CrWarning_DateTime_Setting_Result_OK"},
    {SCRSDK::CrWarning_DateTime_Setting_Result_Parameter_Error,
     "CrWarning_DateTime_Setting_Result_Parameter_Error"},
    {SCRSDK::CrWarning_DateTime_Setting_Result_Exclusion_Error,
     "CrWarning_DateTime_Setting_Result_Exclusion_Error"},
    {SCRSDK::CrWarning_DateTime_Setting_Result_System_Error,
     "CrWarning_DateTime_Setting_Result_System_Error"},
    {SCRSDK::CrWarning_Frame_NotUpdated, "CrWarning_Frame_NotUpdated"},
    {SCRSDK::CrWarning_Connect_Already, "CrWarning_Connect_Already"},
    {SCRSDK::CrWarning_Connect_OverLimitOfDevice, "CrWarning_Connect_OverLimitOfDevice"},
    {SCRSDK::CrWarning_Format_Canceled, "CrWarning_Format_Canceled"},
    {SCRSDK::CrWarning_ZoomAndFocusPosition_Invalid, "CrWarning_ZoomAndFocusPosition_Invalid"},
    {SCRSDK::CrWarning_ZoomAndFocusPosition_DifferentLens,
     "CrWarning_ZoomAndFocusPosition_DifferentLens"},
    {SCRSDK::CrWarning_ZoomAndFocusPosition_InvalidLens,
     "CrWarning_ZoomAndFocusPosition_InvalidLens"},
    {SCRSDK::CrWarning_ContentsTransferMode_Invalid, "CrWarning_ContentsTransferMode_Invalid"},
    {SCRSDK::CrWarning_ContentsTransferMode_DeviceBusy,
     "CrWarning_ContentsTransferMode_DeviceBusy"},
    {SCRSDK::CrWarning_ContentsTransferMode_StatusError,
     "CrWarning_ContentsTransferMode_StatusError"},
    {SCRSDK::CrWarning_ContentsTransferMode_CanceledFromCamera,
     "CrWarning_ContentsTransferMode_CanceledFromCamera"},
    {SCRSDK::CrWarning_ContentsTransferCancel_Success, "CrWarning_ContentsTransferCancel_Success"},
    {SCRSDK::CrWarning_ContentsTransferCancel_Error, "CrWarning_ContentsTransferCancel_Error"},
    {SCRSDK::CrWarning_CameraSettings_Read_Result_Invalid,
     "CrWarning_CameraSettings_Read_Result_Invalid"},
    {SCRSDK::CrWarning_CameraSettings_Read_Result_OK, "CrWarning_CameraSettings_Read_Result_OK"},
    {SCRSDK::CrWarning_CameraSettings_Read_Result_NG, "CrWarning_CameraSettings_Read_Result_NG"},
    {SCRSDK::CrWarning_CameraSettings_Save_Result_NG, "CrWarning_CameraSettings_Save_Result_NG"},
    {SCRSDK::CrWarning_RequestDisplayStringList_Success,
     "CrWarning_RequestDisplayStringList_Success"},
    {SCRSDK::CrWarning_RequestDisplayStringList_Error, "CrWarning_RequestDisplayStringList_Error"},
    {SCRSDK::CrWarning_DisplayListChanged_BaseLook_AELevelOffsetExposureValueList,
     "CrWarning_DisplayListChanged_BaseLook_AELevelOffsetExposureValueList"},
    {SCRSDK::CrWarning_DisplayListChanged_BaseLook_InputDisplayList,
     "CrWarning_DisplayListChanged_BaseLook_InputDisplayList"},
    {SCRSDK::CrWarning_DisplayListChanged_BaseLook_NameDisplayList,
     "CrWarning_DisplayListChanged_BaseLook_NameDisplayList"},
    {SCRSDK::CrWarning_DisplayListChanged_BaseLook_OutputDisplayList,
     "CrWarning_DisplayListChanged_BaseLook_OutputDisplayList"},
    {SCRSDK::CrWarning_DisplayListChanged_SceneFile_NameDisplayList,
     "CrWarning_DisplayListChanged_SceneFile_NameDisplayList"},
    {SCRSDK::CrWarning_DisplayListChanged_ShootingMode_CinemaColorGamutDisplayList,
     "CrWarning_DisplayListChanged_ShootingMode_CinemaColorGamutDisplayList"},
    {SCRSDK::CrWarning_DisplayListChanged_ShootingMode_TargetDisplayDisplayList,
     "CrWarning_DisplayListChanged_ShootingMode_TargetDisplayDisplayList"},
    {SCRSDK::CrWarning_DisplayListChanged_Camera_GainBaseISODisplayList,
     "CrWarning_DisplayListChanged_Camera_GainBaseISODisplayList"},
    {SCRSDK::CrWarning_DisplayListChanged_Video_EIGainDisplayList,
     "CrWarning_DisplayListChanged_Video_EIGainDisplayList"},
    {SCRSDK::CrWarning_DisplayListChanged_Button_AssignDisplayList,
     "CrWarning_DisplayListChanged_Button_AssignDisplayList"},
    {SCRSDK::CrWarning_DisplayListChanged_Button_AssignShortDisplayList,
     "CrWarning_DisplayListChanged_Button_AssignShortDisplayList"},
    {SCRSDK::CrWarning_MediaProfileChanged_Slot1, "CrWarning_MediaProfileChanged_Slot1"},
    {SCRSDK::CrWarning_MediaProfileChanged_Slot2, "CrWarning_MediaProfileChanged_Slot2"},
    {SCRSDK::CrWarning_LensInformationChanged, "CrWarning_LensInformationChanged"},
    {SCRSDK::CrWarning_RequestLensInformation_Result_Success,
     "CrWarning_RequestLensInformation_Result_Success"},
    {SCRSDK::CrWarning_RequestLensInformation_Result_DeviceBusy,
     "CrWarning_RequestLensInformation_Result_DeviceBusy"},
    {SCRSDK::CrWarning_RequestLensInformation_Result_Error,
     "CrWarning_RequestLensInformation_Result_Error"},
    {SCRSDK::CrWarning_DisplayListChanged_CreativeLook_NameDisplayList,
     "CrWarning_DisplayListChanged_CreativeLook_NameDisplayList"},
    {SCRSDK::CrWarning_CustomWBCapture_Result_Invalid, "CrWarning_CustomWBCapture_Result_Invalid"},
    {SCRSDK::CrWarning_CustomWBCapture_Result_OK, "CrWarning_CustomWBCapture_Result_OK"},
    {SCRSDK::CrWarning_CustomWBCapture_Result_NG, "CrWarning_CustomWBCapture_Result_NG"},
    {SCRSDK::CrWarning_ImportLUTFile_Result_Invalid, "CrWarning_ImportLUTFile_Result_Invalid"},
    {SCRSDK::CrWarning_ImportLUTFile_Result_OK, "CrWarning_ImportLUTFile_Result_OK"},
    {SCRSDK::CrWarning_ImportLUTFile_Result_NG, "CrWarning_ImportLUTFile_Result_NG"},
    {SCRSDK::CrWarning_ImportLUTFile_Result_InvalidFileName,
     "CrWarning_ImportLUTFile_Result_InvalidFileName"},
    {SCRSDK::CrWarning_ImportLUTFile_Result_DeviceBusy,
     "CrWarning_ImportLUTFile_Result_DeviceBusy"},
    {SCRSDK::CrWarning_ImportLUTFile_Result_DeviceStorageFull,
     "CrWarning_ImportLUTFile_Result_DeviceStorageFull"},
    {SCRSDK::CrWarning_ImportLUTFile_Result_InvalidParameter,
     "CrWarning_ImportLUTFile_Result_InvalidParameter"},
    {SCRSDK::CrWarning_ImportLUTFile_Result_InvalidFile,
     "CrWarning_ImportLUTFile_Result_InvalidFile"},
    {SCRSDK::CrWarning_FTPTransferSetting_Save_Result_NG,
     "CrWarning_FTPTransferSetting_Save_Result_NG"},
    {SCRSDK::CrWarning_FTPTransferSetting_Save_Result_DeviceBusy,
     "CrWarning_FTPTransferSetting_Save_Result_DeviceBusy"},
    {SCRSDK::CrWarning_FTPTransferSetting_SaveRead_PasswordLengthOverMax,
     "CrWarning_FTPTransferSetting_SaveRead_PasswordLengthOverMax"},
    {SCRSDK::CrWarning_FTPTransferSetting_SaveRead_PasswordIncludesInvalidCharacter,
     "CrWarning_FTPTransferSetting_SaveRead_PasswordIncludesInvalidCharacter"},
    {SCRSDK::CrWarning_RequestFTPServerSettingList_Success,
     "CrWarning_RequestFTPServerSettingList_Success"},
    {SCRSDK::CrWarning_RequestFTPServerSettingList_DeviceBusy,
     "CrWarning_RequestFTPServerSettingList_DeviceBusy"},
    {SCRSDK::CrWarning_RequestFTPServerSettingList_Error,
     "CrWarning_RequestFTPServerSettingList_Error"},
    {SCRSDK::CrWarning_SetFTPServerSetting_Result_Invalid,
     "CrWarning_SetFTPServerSetting_Result_Invalid"},
    {SCRSDK::CrWarning_SetFTPServerSetting_Result_OK, "CrWarning_SetFTPServerSetting_Result_OK"},
    {SCRSDK::CrWarning_SetFTPServerSetting_Result_NG, "CrWarning_SetFTPServerSetting_Result_NG"},
    {SCRSDK::CrWarning_SetFTPServerSetting_Result_DeviceBusy,
     "CrWarning_SetFTPServerSetting_Result_DeviceBusy"},
    {SCRSDK::CrWarning_RequestFTPJobList_Result_Success,
     "CrWarning_RequestFTPJobList_Result_Success"},
    {SCRSDK::CrWarning_RequestFTPJobList_Result_DeviceBusy,
     "CrWarning_RequestFTPJobList_Result_DeviceBusy"},
    {SCRSDK::CrWarning_RequestFTPJobList_Result_Error, "CrWarning_RequestFTPJobList_Result_Error"},
    {SCRSDK::CrWarning_ControlFTPJobList_Set_Result_Invalid,
     "CrWarning_ControlFTPJobList_Set_Result_Invalid"},
    {SCRSDK::CrWarning_ControlFTPJobList_Set_Result_OK,
     "CrWarning_ControlFTPJobList_Set_Result_OK"},
    {SCRSDK::CrWarning_ControlFTPJobList_Set_Result_NG,
     "CrWarning_ControlFTPJobList_Set_Result_NG"},
    {SCRSDK::CrWarning_ControlFTPJobList_Set_Result_DeviceBusy,
     "CrWarning_ControlFTPJobList_Set_Result_DeviceBusy"},
    {SCRSDK::CrWarning_ControlFTPJobList_Delete_Result_Invalid,
     "CrWarning_ControlFTPJobList_Delete_Result_Invalid"},
    {SCRSDK::CrWarning_ControlFTPJobList_Delete_Result_OK,
     "CrWarning_ControlFTPJobList_Delete_Result_OK"},
    {SCRSDK::CrWarning_ControlFTPJobList_Delete_Result_NG,
     "CrWarning_ControlFTPJobList_Delete_Result_NG"},
    {SCRSDK::CrWarning_ControlFTPJobList_Delete_Result_DeviceBusy,
     "CrWarning_ControlFTPJobList_Delete_Result_DeviceBusy"},
    {SCRSDK::CrWarning_ControlFTPJobList_Suspend_Result_Invalid,
     "CrWarning_ControlFTPJobList_Suspend_Result_Invalid"},
    {SCRSDK::CrWarning_ControlFTPJobList_Suspend_Result_OK,
     "CrWarning_ControlFTPJobList_Suspend_Result_OK"},
    {SCRSDK::CrWarning_ControlFTPJobList_Suspend_Result_NG,
     "CrWarning_ControlFTPJobList_Suspend_Result_NG"},
    {SCRSDK::CrWarning_ControlFTPJobList_Suspend_Result_DeviceBusy,
     "CrWarning_ControlFTPJobList_Suspend_Result_DeviceBusy"},
    {SCRSDK::CrWarning_ControlFTPJobList_Resume_Result_Invalid,
     "CrWarning_ControlFTPJobList_Resume_Result_Invalid"},
    {SCRSDK::CrWarning_ControlFTPJobList_Resume_Result_OK,
     "CrWarning_ControlFTPJobList_Resume_Result_OK"},
    {SCRSDK::CrWarning_ControlFTPJobList_Resume_Result_NG,
     "CrWarning_ControlFTPJobList_Resume_Result_NG"},
    {SCRSDK::CrWarning_ControlFTPJobList_Resume_Result_DeviceBusy,
     "CrWarning_ControlFTPJobList_Resume_Result_DeviceBusy"},
    {SCRSDK::CrWarning_MovieRecordingOperation_Result_Invalid,
     "CrWarning_MovieRecordingOperation_Result_Invalid"},
    {SCRSDK::CrWarning_MovieRecordingOperation_Result_OK,
     "CrWarning_MovieRecordingOperation_Result_OK"},
    {SCRSDK::CrWarning_MovieRecordingOperation_Result_NG,
     "CrWarning_MovieRecordingOperation_Result_NG"},
    {SCRSDK::CrWarning_FocusPosition_Result_Invalid, "CrWarning_FocusPosition_Result_Invalid"},
    {SCRSDK::CrWarning_FocusPosition_Result_OK, "CrWarning_FocusPosition_Result_OK"},
    {SCRSDK::CrWarning_FocusPosition_Result_NG, "CrWarning_FocusPosition_Result_NG"},
    {SCRSDK::CrWarning_Reserved1, "CrWarning_Reserved1"},
    {SCRSDK::CrWarning_DisplayListChanged_FTP_ServerNameDisplayList,
     "CrWarning_DisplayListChanged_FTP_ServerNameDisplayList"},
    {SCRSDK::CrWarning_DisplayListChanged_FTP_UpLoadDirectoryDisplayList,
     "CrWarning_DisplayListChanged_FTP_UpLoadDirectoryDisplayList"},
    {SCRSDK::CrWarning_DisplayListChanged_FTP_JobStatusDisplayList,
     "CrWarning_DisplayListChanged_FTP_JobStatusDisplayList"},
    {SCRSDK::CrWarning_Reserved3, "CrWarning_Reserved3"},
    {SCRSDK::CrWarning_Reserved4, "CrWarning_Reserved4"},
    {SCRSDK::CrWarning_Reserved5, "CrWarning_Reserved5"},
    {SCRSDK::CrWarning_Reserved6, "CrWarning_Reserved6"},
    {SCRSDK::CrWarning_DisplayListChanged_IPTCMetadataDisplayList,
     "CrWarning_DisplayListChanged_IPTCMetadataDisplayList"},
    {SCRSDK::CrWarning_DisplayListChanged_SubjectRecognitionAFDisplayList,
     "CrWarning_DisplayListChanged_SubjectRecognitionAFDisplayList"},
    {SCRSDK::CrWarning_MediaProfileChanged_Slot3, "CrWarning_MediaProfileChanged_Slot3"},
    {SCRSDK::CrWarning_ControlMonitoring_Result_Start_Failed,
     "CrWarning_ControlMonitoring_Result_Start_Failed"},
    {SCRSDK::CrWarning_ControlMonitoring_Result_Stop_Failed,
     "CrWarning_ControlMonitoring_Result_Stop_Failed"},
    {SCRSDK::CrWarning_ControlMonitoring_Result_Invalid,
     "CrWarning_ControlMonitoring_Result_Invalid"},
    {SCRSDK::CrWarning_ControlMonitoring_Result_SystemError,
     "CrWarning_ControlMonitoring_Result_SystemError"},
    {SCRSDK::CrWarning_ControlMonitoring_Result_MaximumNumberSimultaneousDeliveries,
     "CrWarning_ControlMonitoring_Result_MaximumNumberSimultaneousDeliveries"},
    {SCRSDK::CrWarning_ControlMonitoring_Result_ExclusiveError,
     "CrWarning_ControlMonitoring_Result_ExclusiveError"},
    {SCRSDK::CrWarning_ControlMonitoring_Result_AlreadyStartedInDifferentType,
     "CrWarning_ControlMonitoring_Result_AlreadyStartedInDifferentType"},
    {SCRSDK::CrWarning_ControlMonitoring_Result_MonitoringStopped,
     "CrWarning_ControlMonitoring_Result_MonitoringStopped"},
    {SCRSDK::CrWarning_ControlMonitoring_Result_InvalidParameter,
     "CrWarning_ControlMonitoring_Result_InvalidParameter"},
    {SCRSDK::CrWarning_ControlMonitoring_StatusChanged,
     "CrWarning_ControlMonitoring_StatusChanged"},
    {SCRSDK::CrWarning_ControlMonitoring_LostReceiving,
     "CrWarning_ControlMonitoring_LostReceiving"},
    {SCRSDK::CrWarning_RequestZoomAndFocusPreset_Result_Success,
     "CrWarning_RequestZoomAndFocusPreset_Result_Success"},
    {SCRSDK::CrWarning_RequestZoomAndFocusPreset_Result_DeviceBusy,
     "CrWarning_RequestZoomAndFocusPreset_Result_DeviceBusy"},
    {SCRSDK::CrWarning_RequestZoomAndFocusPreset_Result_Error,
     "CrWarning_RequestZoomAndFocusPreset_Result_Error"},
    {SCRSDK::CrWarning_ZoomAndFocusPresetChanged, "CrWarning_ZoomAndFocusPresetChanged"},
    {SCRSDK::CrWarning_CautionDisplay, "CrWarning_CautionDisplay"},
    {SCRSDK::CrWarningExt_Unknown, "CrWarningExt_Unknown"},
    {SCRSDK::CrWarningExt_AFStatus, "CrWarningExt_AFStatus"},
    {SCRSDK::CrWarningExt_OperationResults, "CrWarningExt_OperationResults"},
    {SCRSDK::CrWarningExt_AFStatusParam_Unlocked, "CrWarningExt_AFStatusParam_Unlocked"},
    {SCRSDK::CrWarningExt_AFStatusParam_Focused_AF_S, "CrWarningExt_AFStatusParam_Focused_AF_S"},
    {SCRSDK::CrWarningExt_AFStatusParam_NotFocused_AF_S,
     "CrWarningExt_AFStatusParam_NotFocused_AF_S"},
    {SCRSDK::CrWarningExt_AFStatusParam_TrackingSubject_AF_C,
     "CrWarningExt_AFStatusParam_TrackingSubject_AF_C"},
    {SCRSDK::CrWarningExt_AFStatusParam_Focused_AF_C, "CrWarningExt_AFStatusParam_Focused_AF_C"},
    {SCRSDK::CrWarningExt_AFStatusParam_NotFocused_AF_C,
     "CrWarningExt_AFStatusParam_NotFocused_AF_C"},
    {SCRSDK::CrWarningExt_OperationResultsParam_Invalid,
     "CrWarningExt_OperationResultsParam_Invalid"},
    {SCRSDK::CrWarningExt_OperationResultsParam_OK, "CrWarningExt_OperationResultsParam_OK"},
    {SCRSDK::CrWarningExt_OperationResultsParam_NG, "CrWarningExt_OperationResultsParam_NG"},
    {SCRSDK::CrWarningExt_OperationResultsParam_InvalidParameterError,
     "CrWarningExt_OperationResultsParam_InvalidParameterError"},
    {SCRSDK::CrWarningExt_OperationResultsParam_CameraStatusError,
     "CrWarningExt_OperationResultsParam_CameraStatusError"},
    {SCRSDK::CrWarningExt_OperationResultsParam_CharacterSizeError,
     "CrWarningExt_OperationResultsParam_CharacterSizeError"},
};

std::string decode(const CrInt32u error) {
  const auto iter = mapErrorCode.find(error);
  if (iter != mapErrorCode.end()) {
    return iter->second;
  } else {
    // This should only be possible if someone updates the SDK without updating the enum definitions
    EYEFUL_LOGI("CrError {0:#x} has no associated string", error);
    return "";
  }
}
} // namespace error2string
